### ISSUE TITLE
Write a function for calculating the cost of labelling positive/negative.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/DataCost#1]
**Issue Overview**

Two fundamental concepts for calculating cost based metrics of labeled data are:

- *C*<sub>*N*</sub>: The cost of labeling every data point as negative.
- *C*<sub>*P*</sub>: The cost of labeling every data point as positive.

**Details of the Above Concepts**

To fully explain the above equations, the following concepts first need to be detailed:

*Basic Notations* - *Prediction Type Counts*: *N*<sub>*TP*</sub>, *N*<sub>*TN*</sub>, *N*<sub>*FP*</sub>, and *N*<sub>*FN*</sub>

First consider a set of data points *D* which has a total of |*P*| positive data points and |*N*| negative data points. If all the data points in *D* were labeled as positive, then |*P*| data points would be *correctly* labeled and |*N*| data points would be *incorrectly* labeled. A more formal way of saying this is that there would be |*P*| *true positive* labels and |*N*| *false positive* labels. Similarly if all the data points in *D* were labeled as negative, then there would be |*N*| true negative labels, and |*P*| false negative labels. To denote the number of true positives, the notation *N*<sub>*TP*</sub> can be used. The same can be done to denote the other labels, that is: *N*<sub>*TN*</sub>, *N*<sub>*FP*</sub>, and *N*<sub>*FN*</sub>.

*Basic Notations* - *The Costs of the Cost Matrix*: *C*<sub>*TP*</sub>, *C*<sub>*TN*</sub>, *C*<sub>*FP*</sub>, and *C*<sub>*FN*

Each type of prediction (See Basic Notations - Prediction Type Counts) has an associated cost. Typically, this is interpreted to be the cost that is incurred as a result of the prediction. For example, consider a task where the goal is to predict whether or not a bug is present in a C++ function. A FN label would mean that the function is predicted to contain no bugs when it actually does. A TN label would mean that the function is correctly predicted as bug-free. Therefore, the cost of a *FN* label will be huge compared to the cost of a *TN* label. The costs can be written using the notation: *C*<sub>*TP*</sub>, *C*<sub>*TN*</sub>, *C*<sub>*FP*</sub>, and *C*<sub>*FN*</sub>. Business experts are typically required to decide correct values for these costs and they are often estimations.

**Equations for Calculating *C*<sub>*N*</sub> and *C*<sub>*P*</sub>**

Given the explanations above in *Basic Notations* - *Prediction Type Counts* and *Basic Notations* - *The Costs of the Cost Matrix*, the values for *C*<sub>*N*</sub> and *C*<sub>*P*</sub> can be calculated as follows:

*C*<sub>*N*</sub> = *N*<sub>*TN*</sub> X *C*<sub>*TN*</sub> + *N*<sub>*FN*</sub> X *C*<sub>*FN*</sub>
*C*<sub>*P*</sub> = *N*<sub>*TP*</sub> X *C*<sub>*TP*</sub> + *N*<sub>*FP*</sub> X *C*<sub>*FP*</sub>

**Tasks to Close Issue**

- [x] Design a function signature for both functions. They can be presented in a reply to this issue.
- [x] Write unit tests for both functions which will sufficiently test the functions.
- [x] Implement both functions.
- [x] Ensure that both functions pass their unit tests.
- [x] Generate documentation.

**Comment by mikesiers** [comment]
The function signatures are:
- cost_labelling_positive(num_positive, num_negative, cost_matrix) : returns float
- cost_labelling_negative(num_positive, num_negative, cost_matrix) : returns float

where cost_matrix is a dictionary containing the costs. 
**For example**:
`cost_matrix = {'TP' : 0, 'TN' : 1, 'FP' : 1, 'FN' : 5}`
