### ISSUE TITLE
Add a "How to Use" section at beginning of ReadMe.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/DataCost#16]
**Overview of this Issue**

To help new users learn how to use the library, a brief "How to Use" section should be included at the beginning of the ReadMe. There should also be a link to the documentation.

**Tasks to Close Issue**

- [x] Decide a good example to show in the instructions. Write the user steps of this example in a reply to this issue.
- [x] Write each step into the ReadMe.
- [x] Link to the documentation using [this](http://htmlpreview.github.io/?https://github.com/mikesiers/DataCost/blob/master/docs/datacost.html).

**Comment by mikesiers** [comment]
**Example to show in the instructions:**

*Step 1:* Install the library.
*Step 2:* Import the library.
*Step 3:* Define a cost matrix.
*Step 4:* Calculate the expected cost for 10 positive records and 100 negative records.
