### ISSUE TITLE
Write a function for calculating expected cost.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/DataCost#2]
**Prerequisite Issues**

- [x] #1 

**Issue Overview**

The expected cost is typically a representation of how much a set of data points can be expected to cost a business. It is represented by the symbol *E*. The equation for *E* is as follows:

![Expected Cost](https://raw.githubusercontent.com/mikesiers/DataCost.py/master/readmeImg/ExpectedCost.gif)

For information on what *C<sub>P</sub>* and *C<sub>N</sub>* represent, see Issue #1.

**Tasks to Close Issue**

- [x] Design a function signature for this function. It can be presented in a reply to this issue.
- [x] Write unit tests for the function which will sufficiently test it.
- [x] Implement the function.
- [x] Ensure that the function passes all unit tests.
- [x] Generate documentation.

**Comment by mikesiers** [comment]
The function signature will be `expected_cost(num_positive, num_negative, cost_matrix)`. It will return a float of the expected cost. This is very similar to the function signature which can be seen in issue #1.

**Comment by mikesiers** [comment]
The work done in commit 49a2a68 was enough to close this issue.
