### ISSUE TITLE
Write a function for calculating expected cost difference after a split.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/DataCost#3]
**Prerequisite Issues**

- [x] #2 

**Issue Overview**

The expected cost *E* has been detailed in Issue #2. After a split, a set of data points has several new sets of class supports, one for each split. The expected cost difference can be calculated as the difference between *E* for the original dataset, and the summed *E* over all splits. The equation for expected cost after a split is as follows:

![Expected Cost After Split](https://raw.githubusercontent.com/mikesiers/DataCost.py/master/readmeImg/ExpectedCostAfterSplit.gif)

Where *k* is the number of splits, C<sub>P</sub><sup>i</sup> is the value of C<sub>P</sub> for the *i*'th split. For details on C<sub>P</sub> and C<sub>N</sub> see Issue #1. For details on *E* see Issue #2.

**Tasks to Close Issue**

- [x] Design a function signature for this function. It can be presented in a reply to this issue.
- [x] Write unit tests for the function which will sufficiently test it.
- [x] Implement the function.
- [x] Ensure that all unit tests are passed.
- [x] Generate documentation.

**Comment by mikesiers** [comment]
The function signature will be: 

- `expected_cost_after_split(class_supports, cost_matrix)` : returns a `float`

where `class_supports` is a list of python dictionaries where each dictionary is in the form: 
`{'positive' : 6, 'negative' : 3}`. The values 3 and 6 are examples.
