### ISSUE TITLE
Write a function for calculating the expected cost per data point.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/DataCost#4]
**Prerequisite Issues**

- [x] #2 

**Issue Overview**

The expected cost per data point is simply the expected cost for a dataset divided by the number of data points in the dataset. It is a way of normalizing expected cost such that logical comparisons may be made between the expected cost of two datasets of different size.

![Expected Cost Per Data Point](https://raw.githubusercontent.com/mikesiers/DataCost.py/master/readmeImg/ExpectedCostPerDataPoint.gif)

Where |*D*| is the number of records in the dataset *D*. For information on what *E* represents, see Issue #2 .

**Tasks to Close Issue**

- [x] Design a function signature for this function. It can be presented in a reply to this issue.
- [x] Write unit tests for the function which will sufficiently test it.
- [x] Implement the function.
- [x] Ensure all unit tests pass.
- [x] Generate documentation.

**Comment by mikesiers** [comment]
The function signature will be:
`expected_cost_per_record(num_positive, num_negative, cost_matrix)`
These parameters are the same as those for the `expected_cost` function.
