### ISSUE TITLE
Implement total_cost function.

### ISSUE THREAD

**Issue by mikesiers** [mikesiers/DataCost#6]
**Prerequisite Issues**

- [x] #1 

**Issue Overview**

The total cost (*C*<sub>*T*</sub>) is simply the number of TPs, FPs etc which are incurred, multiplied by the corresponding costs. It is calculated as follows:

*C*<sub>*T*</sub> = *N*<sub>*TN*</sub> X *C*<sub>*TN*</sub> + *N*<sub>*FN*</sub> X *C*<sub>*FN*</sub> + *N*<sub>*TP*</sub> X *C*<sub>*TP*</sub> + *N*<sub>*FP*</sub> X *C*<sub>*FP*</sub>

The notation used here is explained in #1.

**Tasks to Close Issue**

- [x] Design a function signature for this function. It can be presented in a reply to this issue.
- [x] Write unit tests for the function which will sufficiently test it.
- [x] Implement the function.
- [x] Ensure all unit tests pass.
- [x] Generate documentation.
- [x] Add description to README.
- [x] Update the PyPi package.

**Comment by mikesiers** [comment]
*Function Signature*

total_cost(num_positive, num_negative, cost_matrix) : returns float

- cost_matrix is a dictionary containing the costs. 
**For example**:
`cost_matrix = {'TP' : 0, 'TN' : 1, 'FP' : 1, 'FN' : 5}`
- num_positive and num_negative are the number of positive and negative records.

**Comment by mikesiers** [comment]
The PyPi package has been updated: https://pypi.python.org/pypi?:action=display&name=DataCost&version=1.01
